version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ec2-user/discord/DiscordBot
permissions:
  - object: /home/ec2-user/discord/DiscordBot
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 60
      runas: root
      